# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: History of Computer Communications
email:  jimhistory@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A History of Computer Communications from the Development 
  of the Modem to the Early Years of the Internet. By James Pelkey. 
baseurl: "/History-of-Computer-Communications"
url: ""
collections:
    sections:
        output: true
        permalink: /section/:path/
    chapters:
        output: false
    market_sectors:
        output: false
    companies:
        output: false
    interviews:
        output: true
        permalink: /interview/:path/
    interview_organizations:
        output: false

defaults:
  -
    scope:
      path: ""
      type: sections
    values:
      layout: template
  -
    scope:
      path: ""
      type: interviews
    values:
      layout: template

include:
  - _chapters
  - _sections

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-include-cache

encoding: UTF-8

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
